[package]
name = "fivem-utility"
version = "0.2.3"
authors = ["Lily H <bsalarius@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.1"
colored = "1.9.3"
reqwest = { version = "0.10.6", features = ["blocking"] }
regex = "1.3.9"
