[package]
name = "fivem-utility"
version = "0.2.4"
authors = ["Lily H <bsalarius@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
colored = "2.0.0"
reqwest = { version = "0.10.7", features = ["blocking"] }
regex = "1.3.9"
